import Navigation from "../components/navigation"

export const metadata = {
  title: 'Home | The New York Times Best Seller list',
  description: 'Generated by Next.js',
}

export default function RootLayout({children}: {children: React.ReactNode}) {
  return (
    <html lang="en">
      <body>
        <Navigation />
        {children}
      </body>
    </html>
  )
}
