export const metadata = {
  title: 'Home | The New York Times Best Seller list',
  description: 'Generated by Next.js',
}

export default function Page() {
  return (
    <div>
      <h1>The New York Times Best Seller Explorer</h1>
    </div>
  );
}
